### ISSUE TITLE
question: assigning variable value from file

### ISSUE THREAD

**Issue by anapsix** [thought-machine/please-examples#11]
I'm trying to figure out a way to assign a variable from content of the file and pass it to `docker_image`.
I'm completely new to _Please Build_, and so far, based on examples and everything I've read, I've came up with way to wrap `docker_image()` into new rule `auto_versioned_docker_image()`.

I'm attempting to set `app_version` to `f'$(cat VERSION)'`, where `VERSION` contains `0.1.0`, for example.
Yet, all I'm getting is `BUILD: ### Application VERSION: $(cat VERSION)` in the log, which is how exactly it's passed to `docker_image()`, causing the following error:
```
invalid argument "docker.io/plz-docker-example:" for "-t, --tag" flag: invalid reference format
```

I know I could set the variable via `[buildenv]`, or even `[build] PassEnv`, but I'd like to read it from an arbitrary file.

Any suggestions is appreciated.

```python
subinclude("@pleasings//docker")

def auto_versioned_docker_image(name:str, srcs:list=[], image:str=None,
                 dockerfile:str='Dockerfile', base_image:str='', repo:str='', labels:list=[],
                 run_args:str='', test_only:bool=False, visibility:list=None):
  app_version = f'$(cat VERSION)'
  log.info('### Application VERSION: ' + app_version)
  docker_image(
    name = f'{name}',
    image = f'{image}',
    version = f'{app_version}',
    dockerfile = f'{dockerfile}',
    repo = f'{repo}'
  )

auto_versioned_docker_image(
  name = "plz-docker-example",
  image = "plz-docker-example",
  dockerfile = "Dockerfile",
  repo = "docker.io"
)
```

**Comment by Tatskaari** [comment]
Sorry for the slow reply. For future reference, the main please repo is much more closely monitored. 

You can't run arbitrary commands while parsing a file like that. To get the version into the BUILD language, you will need to do some advanced stuff possibly with post-build functions. You're probably better off forking the docker_image() rules and adjusting them to set the version tag based off the file rather than the version param. 

For anybody interested, the post build function approach might look a bit like this: 
1. Create a build_rule() that takes in VERSION as a src and sets it's cmd to `cmd = "cat $SRCS"`
2. Add a post build function to that buld_rule() that creates your docker_image() rule for you, setting the version based off it's `output` param. 
3. Add that docker image as a dependency so it somehow gets picked up by Please when you add your rule as a dep.
