### ISSUE TITLE
Best way to deal with editor configuration

### ISSUE THREAD

**Issue by mindreframer** [thought-machine/please-examples#2]
Currently I am particularly interested in Go-related setup. 

Current example for go has code for kittenlib / server / client packages in one folder, that confuses all default Go autocomplete setups... Are there any guidelines how you to deal with this?

**Comment by peterebden** [comment]
I didn't really think of autocomplete when I set up the current structure, but it's probably better to choose a more standard Go setup. I'll split them up into separate directories which should make things somewhat better.

In terms of autocomplete for generated code (protos and so forth), that's a little trickier. I've added a small feature to plz which creates `plz-out/go` which you can point GOPATH to to pick up generated code; standard Go tools seem pretty happy with my GOPATH set to: `$PWD:$PWD/plz-out/go:$PWD/plz-out/gen/third_party/go`. That's a bit of a mouthful but does at least work, and gocode seems to be able to complete protos OK for me. It still doesn't get some of the other libraries though because they're one level too deep (i.e. `plz-out/gen/go/lib/lib.a` would need to be `plz-out/gen/go/lib.a`). I'm not sure how best to resolve that right now - https://github.com/linuxerwang/gobazel appears to tackle some similar issues, not sure if that'd help or how easy it'd be to adapt.
