### ISSUE TITLE
build fails: grpc_cpp_plugin not found in PATH /usr/local/bin:/usr/bin:/bin

### ISSUE THREAD

**Issue by fho** [thought-machine/please-examples#4]
Hello,

I tried to buil the examples but it failed with the following error:

```
$ ./pleasew build -p
16:45:56.488   ERROR: //proto:_kitten#protoc: Build failed: grpc_cpp_plugin not found in PATH /usr/local/bin:/usr/bin:/bin: grpc_cpp_plugin not found in PATH /usr/local/bin:/usr/bin:/bin
16:45:56.488   ERROR: //proto:_kitten#protoc failed:
grpc_cpp_plugin not found in PATH /usr/local/bin:/usr/bin:/bin
Build stopped after 130ms. 1 target failed:
    //proto:_kitten#protoc
grpc_cpp_plugin not found in PATH /usr/local/bin:/usr/bin:/bin
```

Is it required to have this grpc_cpp_plugin installed on the host?

**Comment by fho** [comment]
Seems so: https://github.com/thought-machine/please-examples/blob/master/docker/Dockerfile

**Comment by peterebden** [comment]
Unfortunately yes, ideally it would be possible to download a prebuilt version similar to the prebuilt protoc binaries that are provided for protobuf, but gRPC doesn't provide any of those at present.

The Go and Java ones do work independently, but C++ and Python don't at present.

**Comment by fho** [comment]
@peterebden ok, thanks for the confirmation.
It might be helpful to add a note to the README or maybe even not use protobuf in the examples, to make it easier to try them

**Comment by peterebden** [comment]
Good idea, thanks, I've added some notes about dependencies.

I liked the idea of using gRPC for this because it shows off some non-trivial relationships between the languages, but agreed it's not a lightweight dependency. It may be useful to split off another set of easier examples at some point.
For now I've added some instructions on how to test just Go and/or Java since they can work in isolation. I found a minor bug in the process so those commands might not work unless you're on the latest version.
